# A bank of 350 images, in 4000/<n>.png.
compressed = true
bank = true
images = [
    { packed = true },
    { packed = true, tail = "019f" },
    { packed = true, tail = "ff0000" },
    { packed = true, tail = "800100" },
    { packed = true, tail = "00020000" },
    { packed = true, tail = "006b0000" },
    { packed = true, tail = "690d00" },
    { packed = true, tail = "e000000000" },
    { packed = true, tail = "00030000" },
    { packed = true, tail = "003f000000" },
    { packed = true, tail = "e30000" },
    { packed = true, tail = "5e3600" },
    { packed = true, tail = "f6000000" },
    { packed = true, tail = "00ee000000" },
    { packed = true, tail = "f90000" },
    { packed = true, tail = "98170000" },
    { packed = true, tail = "036900" },
    { packed = true, tail = "f04d" },
    { packed = true, tail = "429e" },
    { packed = true, tail = "78dc000000" },
    { packed = true, tail = "03dc0000" },
    { packed = true, tail = "9efe0000" },
    { packed = true, tail = "5f42" },
    { packed = true, tail = "6900" },
    { packed = true, tail = "8936" },
    { packed = true, tail = "eef50000" },
    { packed = true, tail = "4dfd0000" },
    { packed = true, tail = "f30f" },
    { packed = true },
    { packed = true, tail = "04360000" },
    { packed = true, tail = "c8c8000000" },
    { packed = true, tail = "0ff600" },
    { packed = true, tail = "bf00000000" },
    { packed = true, tail = "0fe9000000" },
    { packed = true, tail = "0098000000" },
    { packed = true },
    { packed = true, tail = "03be" },
    { packed = true, tail = "b99600" },
    { packed = true, tail = "0063000000" },
    { packed = true, tail = "8963" },
    { packed = true },
    { packed = true, tail = "5e4d000000" },
    { packed = true },
    { packed = true, tail = "6c9e00" },
    { packed = true, tail = "6363" },
    { packed = true, tail = "f90000" },
    { packed = true, tail = "006300" },
    { packed = true },
    { packed = true, tail = "f7000000" },
    { packed = true },
    { packed = true, tail = "0005000000" },
    { packed = true, tail = "190000" },
    { packed = true, tail = "fc0000" },
    { packed = true, tail = "0015000000" },
    { packed = true, tail = "801000" },
    { packed = true, tail = "004200" },
    { packed = true, tail = "002b0000" },
    { packed = true, tail = "001a00" },
    { packed = true, tail = "8100000000" },
    { packed = true, tail = "3560000000" },
    { packed = true, tail = "e3e30000" },
    { packed = true, tail = "fae0" },
    { packed = true, tail = "8600000000" },
    { packed = true, tail = "4a5500" },
    { packed = true, tail = "8e8e0000" },
    { packed = true, tail = "6d6d" },
    { packed = true, tail = "733c0000" },
    { packed = true, tail = "428900" },
    { packed = true, tail = "084b000000" },
    { packed = true, tail = "4b7300" },
    { packed = true, tail = "9900000000" },
    { packed = true, tail = "04fd0000" },
    { packed = true, tail = "746d" },
    { packed = true, tail = "ecce000000" },
    { packed = true, tail = "0505" },
    { packed = true, tail = "002f" },
    { packed = true, tail = "8c9f000000" },
    { packed = true },
    { packed = true, tail = "8344000000" },
    { packed = true, tail = "8f890000" },
    { packed = true, tail = "5379000000" },
    { packed = true, tail = "2f2f00" },
    { packed = true, tail = "ced5" },
    { packed = true, tail = "808b" },
    { packed = true, tail = "aa00000000" },
    { packed = true, tail = "528300" },
    { packed = true, tail = "99fb" },
    { packed = true, tail = "6e4100" },
    { packed = true, tail = "2f60000000" },
    { packed = true, tail = "2f550000" },
    { packed = true, tail = "81a00000" },
    { packed = true, tail = "3980000000" },
    { packed = true, tail = "5d5d000000" },
    { packed = true, tail = "4b7300" },
    { packed = true, tail = "46090000" },
    { packed = true, tail = "6c8e000000" },
    { packed = true, tail = "6e400000" },
    { packed = true, tail = "c88e00" },
    { packed = true, tail = "2828" },
    { packed = true, tail = "88cd00" },
    { packed = true, tail = "5d1a0000" },
    { packed = true, tail = "5749" },
    { packed = true, tail = "433f000000" },
    { packed = true, tail = "ebbe" },
    { packed = true, tail = "6c2f00" },
    { packed = true, tail = "3c3c0000" },
    { packed = true, tail = "4b84" },
    { packed = true, tail = "0003" },
    { packed = true, tail = "602f000000" },
    { packed = true, tail = "6c4a0000" },
    { packed = true, tail = "80000000" },
    { packed = true, tail = "9c00" },
    { packed = true, tail = "6c8c00" },
    { packed = true, tail = "71c1000000" },
    { packed = true, tail = "6e79000000" },
    { packed = true, tail = "a0c50000" },
    { packed = true, tail = "960200" },
    { packed = true },
    { packed = true, tail = "497a0000" },
    { packed = true },
    { packed = true, tail = "d5ea0000" },
    { packed = true, tail = "c56e" },
    { packed = true, tail = "cbcb00" },
    { packed = true, tail = "8e1c000000" },
    { packed = true, tail = "6d6800" },
    { packed = true, tail = "8100" },
    { packed = true, tail = "94c50000" },
    { packed = true, tail = "9696000000" },
    { packed = true, tail = "0f3c" },
    { packed = true, tail = "67670000" },
    { packed = true, tail = "6e55" },
    { packed = true, tail = "886e00" },
    { packed = true, tail = "a9bf0000" },
    { packed = true, tail = "cd06000000" },
    { packed = true, tail = "bfbf" },
    { packed = true, tail = "6d7400" },
    { packed = true, tail = "bdcb" },
    { packed = true, tail = "495d000000" },
    { packed = true, tail = "89c2000000" },
    { packed = true, tail = "96c50000" },
    { packed = true, tail = "a37a000000" },
    { packed = true, tail = "0e4b0000" },
    { packed = true, tail = "178c000000" },
    { packed = true, tail = "42530000" },
    { packed = true, tail = "cdf200" },
    { packed = true, tail = "8484" },
    { packed = true, tail = "4b82000000" },
    { packed = true, tail = "cdb30000" },
    { packed = true, tail = "8868" },
    { packed = true, tail = "0012" },
    { packed = true, tail = "94e00000" },
    { packed = true, tail = "4b5d0000" },
    { packed = true, tail = "83750000" },
    { packed = true, tail = "8100" },
    { packed = true, tail = "9fb3" },
    { packed = true, tail = "417900" },
    { packed = true, tail = "4484000000" },
    { packed = true, tail = "5399000000" },
    { packed = true, tail = "333c0000" },
    { packed = true, tail = "885d000000" },
    { packed = true, tail = "8100000000" },
    { packed = true, tail = "95950000" },
    { packed = true, tail = "c5c50000" },
    { packed = true, tail = "1f7e00" },
    { packed = true, tail = "40850000" },
    { packed = true, tail = "0a6d00" },
    { packed = true, tail = "b4b4000000" },
    { packed = true, tail = "079e0000" },
    { packed = true, tail = "0606000000" },
    { packed = true, tail = "c25d000000" },
    { packed = false },
    { packed = true, tail = "8340" },
    { packed = true, tail = "abab000000" },
    { packed = true, tail = "e30500" },
    { packed = true, tail = "967a000000" },
    { packed = true, tail = "fae0" },
    { packed = true, tail = "7a7a00" },
    { packed = true, tail = "899f00" },
    { packed = true, tail = "8896" },
    { packed = true, tail = "6c5d0000" },
    { packed = true, tail = "6c8e00" },
    { packed = true, tail = "00140000" },
    { packed = true, tail = "336000" },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = true, tail = "6ea400" },
    { packed = true, tail = "8395000000" },
    { packed = true, tail = "6873000000" },
    { packed = false },
    { packed = true, tail = "5d5d000000" },
    { packed = true, tail = "7342" },
    { packed = false },
    { packed = true },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = true, tail = "e9d80000" },
    { packed = true, tail = "dbdb" },
    { packed = true, tail = "8c79000000" },
    { packed = true, tail = "2cc0" },
    { packed = true, tail = "7a960000" },
    { packed = true, tail = "bfc1000000" },
    { packed = true, tail = "b965" },
    { packed = true, tail = "46c4000000" },
    { packed = true, tail = "aa00000000" },
    { packed = true, tail = "8e8e000000" },
    { packed = true, tail = "bdbd0000" },
    { packed = true, tail = "c580000000" },
    { packed = true, tail = "887a" },
    { packed = true, tail = "799400" },
    { packed = true, tail = "8484" },
    { packed = true, tail = "0004000000" },
    { packed = true, tail = "55b300" },
    { packed = true, tail = "554300" },
    { packed = true },
    { packed = true, tail = "6c41" },
    { packed = true, tail = "556200" },
    { packed = true, tail = "cde30000" },
    { packed = true },
    { packed = true, tail = "6e88" },
    { packed = true, tail = "cd83" },
    { packed = true, tail = "6c6e" },
    { packed = true, tail = "800000" },
    { packed = true, tail = "528000" },
    { packed = true, tail = "7d490000" },
    { packed = true, tail = "8a00000000" },
    { packed = true, tail = "4b680000" },
    { packed = true, tail = "889600" },
    { packed = true, tail = "495d000000" },
    { packed = true, tail = "aa89000000" },
    { packed = true, tail = "6d8c0000" },
    { packed = true, tail = "a3ae000000" },
    { packed = true, tail = "5db3" },
    { packed = true, tail = "0971" },
    { packed = true, tail = "792f00" },
    { packed = true, tail = "6e9400" },
    { packed = true, tail = "7955000000" },
    { packed = true, tail = "b48e0000" },
    { packed = true, tail = "0012" },
    { packed = true, tail = "deaa0000" },
    { packed = true, tail = "c5be" },
    { packed = true, tail = "870000" },
    { packed = true, tail = "cdb30000" },
    { packed = true, tail = "5d550000" },
    { packed = true, tail = "b3b300" },
    { packed = true, tail = "5a3c00" },
    { packed = true, tail = "0018" },
    { packed = true, tail = "8ea0" },
    { packed = true, tail = "a473000000" },
    { packed = true, tail = "1883000000" },
    { packed = true, tail = "2f330000" },
    { packed = true, tail = "42550000" },
    { packed = true, tail = "49670000" },
    { packed = true, tail = "55af00" },
    { packed = true, tail = "8c00000000" },
]
