/*
 * lilly's functions and globals: the declarations only its code and
 * its callers need (shared types and the rest are in zoombinis.h).
 */

#ifndef LILLY_H
#define LILLY_H

extern short lillyStage;
extern short lillyClaim;
void roomViewNotify(View *view, short event);
void lillyNoDraw(View *);
void lillyNoUpdate(View *, short);
void setLillyStage(short value);
short lillyClaimIndex();
void releaseLillyClaim();
void freeResourcePair(long *resources);
short lillyKey(unsigned short event);
void freeLockedResource(long *resource, short *handle);
short footSound(View *view, short which);
void updateLillyBackdrop(View *view, short region);
void startView9002(short n);
void startView9007(short n);
void loadTablePair(long *resources, short id, short **first, short **second);
void deleteHotelTalker();
void placeByHotSpot(View *view);
void freeLockedResources(long *resources, short *handles, short count);
void hopperNotify(View *view, short event);
void placeActorCels3(View *view);
void setRowAndColumn(short b, short a, short n);
void setRowLayerColumn(short a, short b, short c, short n);
extern ShortRect g_4a1dfc;
void startRoomAnimations();
void setLillyLevel(short level);
void updateHotelButtons(View *view, short region);
void updateLillyButtons(View *view, short region);
void lillyActorNotify(View *view, short event);
void loadLockedTable(long *resource, short *handle, short id, short **locked);
extern short g_4ac0e4;
extern short g_4abfc0[];
extern short g_4ac0d6;
extern short g_4ac91e;
extern short g_4ac920;
extern short g_4af0f8;
extern short hotelGoReady;
extern short g_4a1aac;
extern short g_4a1aae;
void lillyNotify60(View *view, short event);
void lillyNotify49(View *view, short event);
void startSnoidInRoom(short id);
void hotelSnoidNotify(View *view, short event);
void showViewOnSquare(short id, short row, short column);
void updateMarkerView(View *view, short region);
void drawHotelButton(short which, short lit, short show);
extern short g_4acdf4[20];
extern short g_4ace1c;
extern short g_4acfee;
extern short g_4acfe8;
extern short hotelLevel;
extern short hotelRoom;
extern short g_4abec6[];
extern short g_4ac0d0;
extern ShortRect g_4a1e32;
extern ImageBank *g_4a1a18;
void drawLillyButton(short which, short lit, short show);
void drawRoomView(View *view);
void startRoomColumnViews();
void checkLillyArrivals();
void updateSquareHighlight(View *view, short region);
extern SceneButton lillyButtons[3];
extern ImageBank *g_4a1d68;
extern ImageBank *g_4ac178;
extern ImageBank *g_4ac17c;
extern short g_4ac0ee;
extern short g_4af0ea;
extern short g_4af102;
extern short g_4aed64[];
extern short g_4af0e8;
extern short g_4a1b1c;
extern short g_4af344;
extern short g_4af346;
extern ShortRect g_4af5a8;
void placeActorCels(View *view);
void placeActorCelsLow(View *view);
void lillyNotify54(View *view, short event);
void loadLillyScripts(long *resources, short *handles, short count);
extern short g_4acff0;
void darkenPalette();
void lillyNotify44(View *view, short event);
void countFeatureValues();
void drawNumberBox(ShortRect rect, short number);
void placeActorCelsHidden(View *view);
void drawIdBox(short id);
void mirrorGrid(short (*grid)[12], short how);
void clearWay(short x);
extern ShortRect g_4a1ae6;
short fitsRoom(short a, short b, short n);
short fitsRoom3d(short a, short b, short c, short n);
void sendSnoidToRoom(short id);
void addLillyViews();
void drawHotelButtons(View *);
void drawLillyButtons(View *);
void flashSquare(View *view);
short hotelKey(unsigned short key);
void closeLilly();
extern short g_4ac13e;
extern short g_4ac136;
extern short g_4ac0ce;
void closeHotel();
void hotelFrame();
extern short g_4a1ab0;
extern unsigned long g_4ac140;
extern ShortRect g_4a19e4;
extern ShortRect g_4a19ec;
extern ShortRect g_4a19f4;
extern ShortRect g_4a19fc;
extern Point g_4a1a1c[16];
extern short g_4af368;
extern long g_4a1b48;
extern long g_4a1b44;
extern long g_4af108[91];
extern short g_4af278[91];
extern long g_4ac928[2];
extern long g_4ac930[2];
extern long g_4ac938[2];
extern long g_4ac98c;
extern short g_4ac994;
extern long g_4ac998;
extern short g_4ac9a0;
extern long g_4ac9a4;
extern short g_4ac9ac;
extern long g_4a1be8;
extern long g_4af364;
extern short g_4abec0;
extern long g_4ac144;
extern long g_4ac148;
extern long g_4ac14c;
extern long g_4ac150;
extern long g_4ac154;
extern long g_4ac158;
extern long g_4ac160;
extern long g_4ac164;
extern long g_4ac168;
extern long g_4ac16c;
extern long g_4ac170;
extern long g_4ac174;
extern long g_4abebc;
extern short g_4ac0c4;
extern short g_4ac0c6;
extern short g_4ac0fe;
extern short g_4ac100;
extern short g_4ac102;
extern short g_4ac104;
extern short g_4ac0fa;
extern PALETTEENTRY g_4ac51c[];
extern short g_4af352;
extern short g_4af34a;
extern short g_4af348;
extern char g_4a1e3a;
extern short *g_4ac188;
extern short *g_4ac18c;
extern short *g_4ac198;
extern short *g_4ac19c;
extern short g_4ac216[25];
extern short g_4ac10e[];
extern short g_4ac0bc;
extern Point g_4a1788[25];
extern Point g_4a17f0[25];
extern short g_4ac510;
extern short g_4ac512;
extern short g_4abdc0[25];
extern ShortRect g_4ac514;
extern short *g_4ac190;
extern short *g_4ac194;
extern short g_4a1a04[5];
extern short g_4a1a0e[5];
extern short g_4ac0ea;
extern short g_4ac0f8;
void placeViewOnSquare(short id, short row, short column);
extern short g_4abec4;
extern short *g_4ac948;
extern short *g_4ac94c;
void drawSquareImage(short row, short column, char offset);
void drawFeatureLabels();
short addLillyActor(short value);
void drawSquare(short row, short column);
void drawBoard(View *);
void drawCursorSquare(View *view);
void placeJumper(View *view);
void placeJumperAt(View *view);
void placeLander(View *view);
void addLillyActors();
short pickNextSquare(View *view);
void hopNotify(View *view, short event);
extern short *g_4ac940;
extern short *g_4ac944;
extern short g_4a1d70[12];
extern short g_4af5a6;
extern short g_4a1db2[13];
extern short g_4a1dcc[12];
extern short g_4a1de4[12];
extern short g_4ac95a[12];
extern short g_4ac972[12];
extern Point g_4a1ca4[];
void dealSquares();
void layOutLillyView(View *view, short region);
extern short g_4a1e3c[12];
extern short g_4a1e56[12];
extern short *g_4af5b0[3];
extern short g_4af5bc[4];
extern short g_4af5c4[4];
extern short g_4af5cc[4];
extern short g_4af5d4[5];
extern short g_4af5de[5];
extern short g_4af5e8[5];
extern short g_4af5f2[6];
extern short g_4af5fe[6];
extern short g_4af60a[6];
extern LillyDeal g_4af616[13];
extern short *g_4ac1a0;
extern short *g_4ac1a4;
void searchStep(short attribute, short layer, short row, short column);
void searchLayer(short attribute, short layer);
void swapSquares();
void flashSwap(View *view);
void lillyViewNotify3(View *view, short event);
void setUpLillyPuzzle();
void lillyClick(short action);
void openHotel();
void otherClick(short action);
extern short g_4af33c;
extern short g_4af664;
extern ShortRect g_4a1cd8[12];
extern ShortRect g_4a1e04;
extern ShortRect g_4a1e0c;
extern short g_4a1f16;
extern short g_4ac924;
extern short g_4ac926;
void dragLillyPiece(View *view, Point where);
extern short g_4af332;
extern short g_4aed22[];
extern short g_4af0ec;
extern short g_4ac922;
extern short g_4ac0c0;
extern short g_4ac0be;
extern short g_4ac0f6;
extern short g_4ac0fc;
extern short g_4ac0f0;
extern short g_4ac138;
extern short g_4ac0c8;
extern short g_4ac0ca;
extern GroupList g_4a1764[1];
extern short g_4ac13a;
extern short g_4ac13c;
extern short g_4ac0f2;
extern short g_4ac0f4;
extern short g_4ac0e6;
extern short g_4ac0dc;
extern short g_4ac0d4;
extern short g_4ac0da;
extern short g_4ac504;
extern short *g_4ac180;
extern short *g_4ac184;
extern short g_4aed3a[];
extern short g_4af33a;
extern short g_4af354;
extern Point g_4a1d40[5];
extern Point g_4a1d54[5];
extern short g_4af104;
extern short g_4af33e;
extern short g_4af340;
extern short g_4af34c;
extern short g_4af34e;
extern short g_4af342;
extern short g_4af360;
extern short g_4af358;
extern char g_4a1e3b;
extern short g_4af8aa;
extern short g_4a1e16[];
extern short g_4a1e28[4];
extern short g_4a1e30;
extern LillySearch g_4ad7e0[];
extern Point g_4af668[];
extern short g_4af8a8;
void lillyNotify30(View *view, short event);
extern short g_4ac91c;
extern short g_4acdca[];
extern short g_4acdf2;
extern short g_4acda0[];
extern short g_4acdc8;
extern short g_4aed14;
void turnGrid(short (*grid)[12], short how);
extern short g_4ac0de;
extern short g_4ac0e0;
extern short g_4ac0e2;
short moveActorDown(View *view);
extern short g_4a1e20[];
extern ImageBank *g_4af5a0;
extern short g_4acec6[];
extern short g_4acfe6;
extern LillyStart g_4aece6[3];
void setUpBoard();
void openLilly();
void lillyFrame();
extern short g_4a1d88;
extern short g_4af5a4;
extern short g_4aed10;
extern short g_4ac958;
extern short g_4af36c;
extern short g_4af100;
extern short g_4af0f0;
extern unsigned long g_4af0fc;
extern short g_4af0fa;
extern short g_4af0f2;
extern short g_4af0f4;
extern short g_4af35e;
extern short g_4af0f6;
extern short g_4aefc0[144];
extern short g_4aed0e[10];
extern short g_4ac9bc[20];
extern short g_4acd76[20];
extern short g_4ace48[20];
extern short g_4acb08[144];
extern short g_4acc2a[144];
extern short g_4af0e2;
extern short g_4af0e4;
extern short g_4acc28;
extern short g_4acd4a;
extern short g_4acfea;
extern short g_4acfec;
extern short g_4ac9e4;
extern short g_4acd9e;
extern short g_4ace70;
extern short g_4a1b40;
extern Point g_4a1bfc[];
extern short g_4af338;
extern GroupList g_4a1bc8[1];
extern short g_4a1ec6[12];
extern short g_4a1ede[14];
extern short g_4a1efa[14];
extern short g_4a1e84[];
extern short (*g_4ac9b0)[12];
extern short (*g_4ac9b4)[12];
extern short (*g_4ac9b8)[12];
extern short g_4a1eae[12];
extern short g_4a1e70[];
extern short g_4a1b1e[];
extern short g_4a1b38[];
void lillyNotify70(View *view, short event);
extern short g_4ac9e6[];
extern short g_4acb06;
extern short g_4aed80[];
extern short g_4af0e0;
extern short g_4aeea0[];
extern short g_4af0e6;
extern short g_4ace1e[20];
extern short g_4ace46;
extern short g_4ac106[4];
extern ChosenSnoids *g_4ac508;
extern short g_4ac0e8;
extern short g_4acff2;
extern short lillyGoReady;
extern short g_4a1d6c;
extern short g_4a1d6e;
extern short g_4ace72[20];
extern short g_4ace9a;
extern short g_4ac0ba;
extern short roomRowValues[25];
extern short roomLayerValues[25];
extern short roomColumnValues[25];
extern short g_4ac310[];
extern short g_4ac40a[];
extern short *actorHotSpotsX;

#endif
