# A bank of 70 images, in 11000/<n>.png.
compressed = true
bank = true
images = [
    { packed = true, tail = "df0000" },
    { packed = true, tail = "fffd00" },
    { packed = true, tail = "eafe00" },
    { packed = true, tail = "e99300" },
    { packed = true, tail = "d10000" },
    { packed = true, tail = "470000" },
    { packed = true, tail = "4b4b00" },
    { packed = true, tail = "00df0000" },
    { packed = true, tail = "9200" },
    { packed = true, tail = "8907000000" },
    { packed = true, tail = "57880000" },
    { packed = true, tail = "26d20000" },
    { packed = true, tail = "069300" },
    { packed = true, tail = "a869" },
    { packed = true, tail = "3a24000000" },
    { packed = true, tail = "b5b50000" },
    { packed = true, tail = "6194" },
    { packed = true, tail = "3a45000000" },
    { packed = true, tail = "946100" },
    { packed = true, tail = "3560000000" },
    { packed = true, tail = "bf40000000" },
    { packed = true, tail = "61560000" },
    { packed = true, tail = "b6b600" },
    { packed = true, tail = "d7d700" },
    { packed = true, tail = "579400" },
    { packed = true, tail = "b6b600" },
    { packed = true, tail = "cccc" },
    { packed = true, tail = "cccc000000" },
    { packed = true, tail = "2e8400" },
    { packed = true, tail = "564c000000" },
    { packed = true, tail = "5656" },
    { packed = true, tail = "bdb20000" },
    { packed = true, tail = "47700000" },
    { packed = true, tail = "c34f0000" },
    { packed = true, tail = "88540000" },
    { packed = true, tail = "988e000000" },
    { packed = true, tail = "87a70000" },
    { packed = true, tail = "bbb0000000" },
    { packed = true, tail = "b6940000" },
    { packed = true, tail = "34a7000000" },
    { packed = true, tail = "00ad00" },
    { packed = true, tail = "06fd00" },
    { packed = true, tail = "c4ad0000" },
    { packed = true, tail = "447000" },
    { packed = true, tail = "3505" },
    { packed = true, tail = "553f0000" },
    { packed = true, tail = "0314" },
    { packed = true, tail = "cccc" },
    { packed = true, tail = "54540000" },
    { packed = true, tail = "c9c900" },
    { packed = true, tail = "b047000000" },
    { packed = true, tail = "43c200" },
    { packed = true, tail = "1e4c000000" },
    { packed = true, tail = "03e6000000" },
    { packed = true, tail = "020300" },
    { packed = true, tail = "a9830000" },
    { packed = true, tail = "18d700" },
    { packed = true, tail = "bcbd00" },
    { packed = true, tail = "8456000000" },
    { packed = true, tail = "e301000000" },
    { packed = true, tail = "3a8e0000" },
    { packed = true, tail = "61ca0000" },
    { packed = true, tail = "bf070000" },
    { packed = true, tail = "bd070000" },
    { packed = true, tail = "3535000000" },
    { packed = true, tail = "5484" },
    { packed = true, tail = "8fff0000" },
    { packed = true, tail = "4b070000" },
    { packed = true, tail = "8a35000000" },
    { packed = true, tail = "4747" },
]
