# A bank of 40 images, in 10000/<n>.png.
compressed = true
bank = true
images = [
    { packed = true, tail = "6192" },
    { packed = true, tail = "43430000" },
    { packed = true, tail = "6f9d00" },
    { packed = true, tail = "2d4300" },
    { packed = true, tail = "2d43" },
    { packed = true, tail = "9ae70000" },
    { packed = true, tail = "d1d1000000" },
    { packed = true, tail = "9862" },
    { packed = true, tail = "62dc" },
    { packed = true, tail = "2d2d00" },
    { packed = true, tail = "9261000000" },
    { packed = true, tail = "2d430000" },
    { packed = true, tail = "434300" },
    { packed = true, tail = "a46e0000" },
    { packed = true, tail = "9d430000" },
    { packed = true, tail = "a5ea000000" },
    { packed = true, tail = "404c000000" },
    { packed = true, tail = "b2920000" },
    { packed = true, tail = "432d000000" },
    { packed = true, tail = "43610000" },
    { packed = true, tail = "84840000" },
    { packed = true, tail = "79d1000000" },
    { packed = true, tail = "432d000000" },
    { packed = true, tail = "656100" },
    { packed = true, tail = "7979000000" },
    { packed = true, tail = "7c61000000" },
    { packed = true, tail = "8484000000" },
    { packed = true, tail = "2d43" },
    { packed = true, tail = "9a8300" },
    { packed = true, tail = "8443" },
    { packed = true, tail = "432d" },
    { packed = true, tail = "2d4300" },
    { packed = true, tail = "d184" },
    { packed = true, tail = "434300" },
    { packed = true, tail = "432d000000" },
    { packed = true, tail = "2d2d00" },
    { packed = true, tail = "43430000" },
    { packed = true, tail = "cfe700" },
    { packed = true, tail = "2d43000000" },
    { packed = true, tail = "e94400" },
]
