# A bank of 64 images, in 10000/<n>.png.
compressed = true
bank = true
images = [
    { packed = true, tail = "000b" },
    { packed = true },
    { packed = true, tail = "000b" },
    { packed = true, tail = "00fd000000" },
    { packed = true, tail = "18a5000000" },
    { packed = true, tail = "a40b00" },
    { packed = true, tail = "85860000" },
    { packed = true, tail = "5545" },
    { packed = true, tail = "0101" },
    { packed = true, tail = "1821000000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "ff9c0000" },
    { packed = true },
    { packed = true, tail = "002600" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "2022000000" },
    { packed = true, tail = "b4200000" },
    { packed = true, tail = "acad0000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "5b75" },
    { packed = true, tail = "a693000000" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "06d6" },
    { packed = true, tail = "6b5e" },
    { packed = true, tail = "453f000000" },
    { packed = true, tail = "052a00" },
    { packed = true, tail = "4e5c0000" },
    { packed = true, tail = "04b7" },
    { packed = true, tail = "10b5" },
    { packed = true, tail = "63000000" },
    { packed = true, tail = "000b" },
    { packed = true, tail = "03c400" },
    { packed = true, tail = "0cb60000" },
    { packed = true, tail = "1a76" },
    { packed = true, tail = "091e0000" },
    { packed = true, tail = "be00000000" },
    { packed = true, tail = "02aa" },
    { packed = true, tail = "99000000" },
    { packed = true },
    { packed = true, tail = "00ff000000" },
    { packed = true, tail = "00ff00" },
    { packed = true, tail = "03030000" },
    { packed = true },
    { packed = true, tail = "00ff" },
    { packed = true, tail = "00bb0000" },
    { packed = true },
    { packed = true, tail = "8187000000" },
    { packed = true, tail = "b0a5" },
    { packed = true, tail = "765400" },
    { packed = false },
    { packed = true, tail = "31550000" },
    { packed = true, tail = "0101" },
    { packed = true },
    { packed = true },
    { packed = false },
    { packed = true },
    { packed = true },
    { packed = false },
    { packed = false },
]
