# A bank of 31 images, in 7000/<n>.png.
compressed = true
bank = true
images = [
    { packed = true },
    { packed = true, tail = "ef000000" },
    { packed = false },
    { packed = true, tail = "fe73" },
    { packed = true, tail = "6492" },
    { packed = true, tail = "fe6f000000" },
    { packed = true, tail = "967900" },
    { packed = true, tail = "fb0000" },
    { packed = true, tail = "007600" },
    { packed = false },
    { packed = true, tail = "fffc0000" },
    { packed = true },
    { packed = true, tail = "7b9c00" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "2626000000" },
    { packed = true, tail = "8b250000" },
    { packed = true },
    { packed = true, tail = "0403000000" },
    { packed = true, tail = "078600" },
    { packed = true, tail = "000e000000" },
    { packed = true, tail = "000d0000" },
    { packed = true, tail = "8000000000" },
    { packed = true, tail = "000400" },
    { packed = true, tail = "03000000" },
    { packed = true, tail = "2002" },
    { packed = true },
    { packed = false },
    { packed = true, tail = "0d000000" },
    { packed = false },
    { packed = true, tail = "00260000" },
]
