# A bank of 32 images, in 1200/<n>.png.
compressed = true
bank = true
images = [
    { packed = true, tail = "3a32" },
    { packed = true, tail = "56030000" },
    { packed = true, tail = "302d0000" },
    { packed = true, tail = "3f3f0000" },
    { packed = true, tail = "080600" },
    { packed = true, tail = "8f700000" },
    { packed = true, tail = "3f34" },
    { packed = true, tail = "8e010000" },
    { packed = true, tail = "2d2e00" },
    { packed = true, tail = "8080" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "8697000000" },
    { packed = true, tail = "033a" },
    { packed = true, tail = "2c30" },
    { packed = true, tail = "302c00" },
    { packed = true },
    { packed = true, tail = "3a680000" },
    { packed = true },
    { packed = true, tail = "65cb" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "2c2e000000" },
    { packed = true, tail = "6342000000" },
    { packed = true, tail = "ceb5" },
    { packed = true, tail = "1121" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "004f000000" },
    { packed = true, tail = "049200" },
    { packed = true, tail = "35060000" },
]
