# A bank of 16 images, in 2100/<n>.png.
compressed = true
bank = true
images = [
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
]
