# A bank of 33 images, in 7000/<n>.png.
compressed = true
bank = true
images = [
    { packed = true, tail = "7afd0000" },
    { packed = true, tail = "2f3e" },
    { packed = true, tail = "2e470000" },
    { packed = true, tail = "7406000000" },
    { packed = true, tail = "3e2f000000" },
    { packed = true, tail = "800000" },
    { packed = true, tail = "312d" },
    { packed = true },
    { packed = true, tail = "2f00" },
    { packed = true, tail = "003f0000" },
    { packed = true, tail = "3100000000" },
    { packed = true, tail = "2d4c00" },
    { packed = true, tail = "800000" },
    { packed = true, tail = "5b59" },
    { packed = true, tail = "322e000000" },
    { packed = true, tail = "323200" },
    { packed = true, tail = "3c2d" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "ca00" },
    { packed = true, tail = "31e70000" },
    { packed = true, tail = "64d0" },
    { packed = true },
    { packed = true, tail = "002f0000" },
    { packed = true, tail = "0db4000000" },
    { packed = true, tail = "9606" },
    { packed = true, tail = "0b8c0000" },
    { packed = true, tail = "840c0000" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "000c0000" },
    { packed = true, tail = "03000000" },
]
