# A bank of 29 images, in 4200/<n>.png.
compressed = true
bank = true
images = [
    { packed = true, tail = "3000000000" },
    { packed = true, tail = "003000" },
    { packed = true, tail = "0030000000" },
    { packed = true, tail = "3a3a000000" },
    { packed = true, tail = "3a3a" },
    { packed = true, tail = "343a" },
    { packed = true },
    { packed = true, tail = "35330000" },
    { packed = true, tail = "86af0000" },
    { packed = true, tail = "0258" },
    { packed = true, tail = "3131000000" },
    { packed = true },
    { packed = true, tail = "0379000000" },
    { packed = true, tail = "3431000000" },
    { packed = true, tail = "022e000000" },
    { packed = true, tail = "040400" },
    { packed = true, tail = "793b" },
    { packed = true, tail = "34040000" },
    { packed = true, tail = "2e020000" },
    { packed = true },
    { packed = true, tail = "330c00" },
    { packed = true, tail = "370b000000" },
    { packed = true, tail = "a660" },
    { packed = true, tail = "3737000000" },
    { packed = true, tail = "37370000" },
    { packed = true, tail = "36680000" },
    { packed = true, tail = "7e0d0000" },
    { packed = true, tail = "7e7e" },
    { packed = true },
]
