# A bank of 180 images, in 8400/<n>.png.
compressed = true
bank = true
images = [
    { packed = true, tail = "ffff0000" },
    { packed = true, tail = "d80000" },
    { packed = true, tail = "001400" },
    { packed = true, tail = "b375000000" },
    { packed = true, tail = "3240" },
    { packed = true, tail = "272c0000" },
    { packed = true, tail = "2402" },
    { packed = true, tail = "2831" },
    { packed = true, tail = "272c000000" },
    { packed = true, tail = "2739000000" },
    { packed = true, tail = "ec000000" },
    { packed = true, tail = "02ff" },
    { packed = true, tail = "302700" },
    { packed = true, tail = "2f48000000" },
    { packed = true },
    { packed = true, tail = "001400" },
    { packed = true, tail = "00090000" },
    { packed = true, tail = "2b2400" },
    { packed = true, tail = "4d4b000000" },
    { packed = true, tail = "2c2f00" },
    { packed = true, tail = "2c2c000000" },
    { packed = true, tail = "3048000000" },
    { packed = true, tail = "f90000" },
    { packed = true, tail = "2e2c00" },
    { packed = true, tail = "2b27" },
    { packed = true, tail = "322e0000" },
    { packed = true, tail = "000400" },
    { packed = true, tail = "00ed000000" },
    { packed = true, tail = "ff2600" },
    { packed = true, tail = "fe0000" },
    { packed = true, tail = "0007" },
    { packed = true, tail = "2731000000" },
    { packed = true, tail = "2a2c00" },
    { packed = true, tail = "265c" },
    { packed = true, tail = "4953000000" },
    { packed = true, tail = "2509000000" },
    { packed = true, tail = "26fd000000" },
    { packed = true, tail = "342e0000" },
    { packed = true, tail = "4e44000000" },
    { packed = true, tail = "fe260000" },
    { packed = true, tail = "fc260000" },
    { packed = true, tail = "2d3a" },
    { packed = true },
    { packed = true, tail = "392d000000" },
    { packed = true },
    { packed = true, tail = "3b2e000000" },
    { packed = true, tail = "2e0b00" },
    { packed = true, tail = "2d3900" },
    { packed = true },
    { packed = true, tail = "4337000000" },
    { packed = true, tail = "832d" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "36360000" },
    { packed = true, tail = "6a69" },
    { packed = true, tail = "3831000000" },
    { packed = true, tail = "7f9a00" },
    { packed = true, tail = "3b3c0000" },
    { packed = true, tail = "362e00" },
    { packed = true, tail = "31350000" },
    { packed = true, tail = "4a38000000" },
    { packed = true, tail = "704b" },
    { packed = true, tail = "363b000000" },
    { packed = true, tail = "745200" },
    { packed = true, tail = "3282" },
    { packed = true, tail = "364e0000" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "0b350000" },
    { packed = true },
    { packed = true, tail = "383600" },
    { packed = true, tail = "8370000000" },
    { packed = true },
    { packed = true, tail = "2d2d0000" },
    { packed = true, tail = "2d0c00" },
    { packed = true },
    { packed = true, tail = "2e3500" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "384a" },
    { packed = true },
    { packed = true, tail = "6a0c0000" },
    { packed = true, tail = "d52d00" },
    { packed = true, tail = "3e3600" },
    { packed = true },
    { packed = true, tail = "2e2e" },
    { packed = true, tail = "43360000" },
    { packed = true, tail = "4748000000" },
    { packed = true },
    { packed = true, tail = "996a0000" },
    { packed = true, tail = "2d36000000" },
    { packed = true },
    { packed = true, tail = "3085000000" },
    { packed = true, tail = "7f510000" },
    { packed = true, tail = "373b" },
    { packed = true, tail = "2d2e" },
    { packed = true, tail = "4a55000000" },
    { packed = true, tail = "2c02000000" },
    { packed = true, tail = "2d5e000000" },
    { packed = true, tail = "40ff0000" },
    { packed = true, tail = "0227000000" },
    { packed = true, tail = "3427" },
    { packed = true, tail = "3c9c" },
    { packed = true, tail = "7fa6" },
    { packed = true },
    { packed = true, tail = "5143000000" },
    { packed = true, tail = "6938000000" },
    { packed = true, tail = "477f000000" },
    { packed = true, tail = "3b31000000" },
    { packed = true, tail = "383800" },
    { packed = true, tail = "6a2d000000" },
    { packed = true, tail = "2d00" },
    { packed = true, tail = "004300" },
    { packed = true, tail = "854a" },
    { packed = true, tail = "4d520000" },
    { packed = true, tail = "2e2e00" },
    { packed = true, tail = "313b0000" },
    { packed = true, tail = "463800" },
    { packed = true, tail = "3836000000" },
    { packed = true },
    { packed = true, tail = "003d" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "3743000000" },
    { packed = true, tail = "36390000" },
    { packed = true, tail = "303000" },
    { packed = true },
    { packed = true, tail = "6643" },
    { packed = true },
    { packed = true, tail = "ff2c0000" },
    { packed = true, tail = "ff3200" },
    { packed = true, tail = "034d0000" },
    { packed = true, tail = "a6830000" },
    { packed = true, tail = "0012" },
    { packed = true, tail = "1893" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "3f540000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "001d" },
    { packed = true, tail = "67440000" },
    { packed = true, tail = "3a3b" },
    { packed = true, tail = "705500" },
    { packed = true, tail = "4a2d0000" },
    { packed = true, tail = "3434" },
    { packed = true, tail = "46710000" },
    { packed = true, tail = "2d2d" },
    { packed = true },
    { packed = true, tail = "37420000" },
    { packed = true, tail = "4643000000" },
    { packed = true, tail = "2e2e" },
    { packed = true, tail = "2f00000000" },
    { packed = true, tail = "898a0000" },
    { packed = true, tail = "383e" },
    { packed = true, tail = "37300000" },
    { packed = true, tail = "373900" },
    { packed = true, tail = "557300" },
    { packed = true, tail = "2d8300" },
    { packed = true, tail = "522d00" },
    { packed = true, tail = "3535" },
    { packed = true, tail = "404d" },
    { packed = true, tail = "384a00" },
    { packed = true, tail = "2d2d00" },
    { packed = true, tail = "3a3900" },
    { packed = true, tail = "8c0000" },
    { packed = true, tail = "352e" },
    { packed = true, tail = "9800000000" },
    { packed = true, tail = "02dc00" },
    { packed = true, tail = "0d4500" },
    { packed = true, tail = "199200" },
    { packed = true, tail = "392d0000" },
    { packed = true, tail = "00130000" },
    { packed = true, tail = "3538000000" },
    { packed = true, tail = "de000000" },
    { packed = true, tail = "1e8e0000" },
    { packed = true, tail = "184c" },
    { packed = true, tail = "4a0d0000" },
]
