"""The table of game globals the port's debug tools can read and write by name.

`write` generates build/port/generated/debug_globals.inc, which
port/debug/zbdebug.cpp includes (when it exists): one entry for every integer
global (`char`, `short`, `int` and `long`, signed or not, alone or as an array
of one or two known dimensions) that decomp/'s headers declare with `extern`
and a source in decomp/ defines. `uv run port build` writes it before
building. The debug commands `get`, `set` and `wait until` use it (handbook:
"Debug tools"), so a script can read a puzzle's state, or wait for it, without
knowing an address.

The headers are ours and plainly written, so a regular expression finds the
declarations (as in `declarations.py`); a global that is declared but not
defined is left out, since the link would fail on it.
"""

import re
from pathlib import Path
from typing import NamedTuple

from zbtools import paths

_TYPES = {
    "char": (1, True),
    "signed char": (1, True),
    "unsigned char": (1, False),
    "short": (2, True),
    "unsigned short": (2, False),
    "int": (4, True),
    "unsigned int": (4, True),
    "long": (4, True),
    "unsigned long": (4, False),
}
_TYPE = r"(?:unsigned\s+|signed\s+)?(?:char|short|int|long)"
_DECLARATION = re.compile(rf"^extern\s+({_TYPE})\s+(\w+)((?:\[\d+\])*)\s*;", re.MULTILINE)
_DEFINITION = re.compile(rf"^(?:{_TYPE})\s+(\w+)(?:\[[^\]]*\])*\s*(?:=|;)", re.MULTILINE)
_DIMENSION = re.compile(r"\[(\d+)\]")

FILE = paths.PORT_GENERATED_DIR / "debug_globals.inc"


class DebugGlobal(NamedTuple):
    name: str
    size: int  # bytes of one element: 1, 2 or 4
    signed: bool
    dimensions: tuple[int, ...]  # () for a scalar; else one or two lengths
    header: str  # the header that declares it


def _canonical(type_: str) -> str:
    return " ".join(type_.split())


def declared(headers: dict[str, str]) -> list[DebugGlobal]:
    """The integer globals the headers (file name -> text) declare."""
    found: list[DebugGlobal] = []
    for header, text in headers.items():
        for match in _DECLARATION.finditer(text):
            size, signed = _TYPES[_canonical(match.group(1))]
            dimensions = tuple(int(n) for n in _DIMENSION.findall(match.group(3)))
            if len(dimensions) <= 2:
                found.append(DebugGlobal(match.group(2), size, signed, dimensions, header))
    return found


def defined(sources: list[str]) -> set[str]:
    """The names of the integer globals the sources define (not extern, not static)."""
    names: set[str] = set()
    for text in sources:
        names.update(match.group(1) for match in _DEFINITION.finditer(text))
    return names


def render(entries: list[DebugGlobal]) -> str:
    """The generated source: the headers' includes and the table."""
    lines = [
        "/* Generated by zbtools.debug_globals: do not edit. */",
        *(f'#include "{header}"' for header in sorted({e.header for e in entries})),
        "",
        "static const DebugGlobal debugGlobals[] = {",
    ]
    for e in sorted(entries, key=lambda e: e.name):
        first, second = (*e.dimensions, 0, 0)[:2]
        lines.append(
            f'    {{"{e.name}", (void *)&{e.name}, {e.size}, {int(e.signed)}, {len(e.dimensions)},'
            f" {first}, {second}}},"
        )
    lines.append("};")
    return "\n".join(lines) + "\n"


def generate(decomp: Path = paths.DECOMP_DIR) -> str:
    """The table for the headers and sources in `decomp`."""
    headers = {p.name: p.read_text() for p in sorted(decomp.glob("*.h"))}
    sources = [p.read_text() for p in sorted(decomp.glob("*.cpp"))]
    have = defined(sources)
    entries = [e for e in declared(headers) if e.name in have]
    unique = {e.name: e for e in entries}  # (a name is declared once; be safe)
    return render(list(unique.values()))


def write(target: Path = FILE, decomp: Path = paths.DECOMP_DIR) -> bool:
    """Writes the table unless it is already there; whether it changed (so the
    build isn't redone for nothing)."""
    text = generate(decomp)
    if target.exists() and target.read_text() == text:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    return True
