r"""Build the "tools CD" that installs QuickTime and the game inside the VM.

The game's own InstallShield installer just unpacks ZBARCHIV.Z into
C:\Program Files\Zoombi32. The game reads no registry settings of its own and
finds its CD by scanning drives, so rather than scripting that installer's GUI,
the tools CD carries the unpacked files and a batch file (ZBINST.BAT) that:

1. runs the QuickTime for Windows installer, with its prompts turned off;
2. copies the game into place and makes its files writable (it saves progress
   in Zoombini.who next to the exe), including the Zoombi32.CFG that the real
   installer would have written (see docs/findings.md);
3. installs the game's font and adds an App Paths entry, so the game can be
   started by typing `zoombi32` in the Start menu's Run box;
4. powers the VM off, which is how `vm install-game` knows it has finished.
"""

import io
import re
from pathlib import Path

import pycdlib
from fontTools.ttLib import TTFont

from zbtools import unpack_isz

# The tools CD is the only CD drive attached while it runs, so it's D:.
TOOLS_CD_DRIVE = "D:"
INSTALL_BAT = rf"{TOOLS_CD_DRIVE}\ZBINST.BAT"
INSTALL_DIR = r"C:\Program Files\Zoombi32"
FONT_FILE = "CORNER.TTF"
# Where `vm run` puts the game disc: it's the VM's only CD drive.
GAME_CD_DRIVE = "D:"

# The game reads the CD and install locations from this INI file, which ships
# empty and is filled in by the original installer (see docs/findings.md).
CFG_FILE = "ZOOMBI32.CFG"
_CFG = f"""[INSTALL]
INSTALLFROMDIR={GAME_CD_DRIVE}\\
INSTALLTODIR={INSTALL_DIR}\\
"""

_QT_INSTALLER = "/QTWSET32/QT32B42.EXE"
_QT_INI = "/QTWSET32/QT32INST.INI"
_GAME_ARCHIVE = "/ZBARCHIV.Z"

# QuickTime installer options that show dialogs. The disc's settings file is
# QT32INST.INI, but the QuickTime 2.1 installer (QT32B42.EXE) only reads an INI
# named after itself, so the tools CD ships it as QT32B42.INI.
_QT_PROMPTS = ["StandAlone", "CheckExistingVersions", "PromptToBegin", "PromptToComplete",
               "SuccessDialog"]  # fmt: skip

_INSTALL_BAT = rf"""@ECHO OFF
REM Generated by zbtools: installs QuickTime and the game, then powers off.
START /W {TOOLS_CD_DRIVE}\QT32\QT32B42.EXE
MD "{INSTALL_DIR}"
COPY {TOOLS_CD_DRIVE}\GAME\*.* "{INSTALL_DIR}" > NUL
ATTRIB -R "{INSTALL_DIR}\*.*"
COPY {TOOLS_CD_DRIVE}\GAME\{FONT_FILE} C:\WINDOWS\FONTS > NUL
ATTRIB -R C:\WINDOWS\FONTS\{FONT_FILE}
REGEDIT /S {TOOLS_CD_DRIVE}\ZBINST.REG
RUNDLL32.EXE SHELL32.DLL,SHExitWindowsEx 5
"""


def _reg_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\") + '"'


def _install_reg(font_name: str) -> str:
    app_paths = r"HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\App Paths"
    fonts = r"HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Fonts"
    return f"""REGEDIT4

[{app_paths}\\ZOOMBI32.EXE]
@={_reg_string(INSTALL_DIR + r"\ZOOMBI32.EXE")}
"Path"={_reg_string(INSTALL_DIR)}

[{fonts}]
{_reg_string(f"{font_name} (TrueType)")}={_reg_string(FONT_FILE)}

"""


def _dos_text(text: str) -> bytes:
    return text.replace("\n", "\r\n").encode("ascii")


def _font_full_name(font: bytes) -> str:
    """The font's full name (name ID 4), which Windows registers fonts under."""
    name = TTFont(io.BytesIO(font))["name"].getDebugName(4)
    if not isinstance(name, str):
        raise ValueError("font has no full name")
    return name


def _without_prompts(qt_ini: bytes) -> bytes:
    text = qt_ini.decode("latin-1")
    for option in _QT_PROMPTS:
        text = re.sub(rf"^(\s*{option}\s*=\s*)1", r"\g<1>0", text, flags=re.MULTILINE)
    return text.encode("latin-1")


def _read(iso: pycdlib.PyCdlib, path: str) -> bytes:
    buf = io.BytesIO()
    iso.get_file_from_iso_fp(buf, iso_path=path)
    return buf.getvalue()


def build_tools_iso(game_iso: Path, out: Path) -> None:
    """Write the tools CD image, reading everything it needs from the game disc."""
    disc = pycdlib.PyCdlib()
    disc.open(str(game_iso))
    try:
        archive = _read(disc, _GAME_ARCHIVE)
        qt_installer = _read(disc, _QT_INSTALLER)
        qt_ini = _read(disc, _QT_INI)
    finally:
        disc.close()

    game_files = {
        entry.path.upper(): unpack_isz.explode(
            archive[entry.offset : entry.offset + entry.compressed_size]
        )
        for entry in unpack_isz.read_archive(archive)
    }
    game_files[CFG_FILE] = _dos_text(_CFG)
    files = {
        "/ZBINST.BAT": _dos_text(_INSTALL_BAT),
        "/ZBINST.REG": _dos_text(_install_reg(_font_full_name(game_files[FONT_FILE]))),
        "/QT32/QT32B42.EXE": qt_installer,
        "/QT32/QT32B42.INI": _without_prompts(qt_ini),
        **{f"/GAME/{name}": data for name, data in game_files.items()},
    }

    iso = pycdlib.PyCdlib()
    iso.new(interchange_level=1, vol_ident="ZBTOOLS")
    try:
        for directory in ("/QT32", "/GAME"):
            iso.add_directory(directory)
        for path, data in files.items():
            iso.add_fp(io.BytesIO(data), len(data), f"{path};1")
        iso.write(str(out))
    finally:
        iso.close()
