# A bank of 232 images, in 1800/<n>.png.
compressed = true
bank = true
images = [
    { packed = true },
    { packed = true, tail = "0015000000" },
    { packed = true, tail = "0a2d000000" },
    { packed = true, tail = "2d000000" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "002d00" },
    { packed = true, tail = "2d8f" },
    { packed = true, tail = "eded0000" },
    { packed = true },
    { packed = true, tail = "2d81" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "115700" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "d8ed00" },
    { packed = true, tail = "83ed0000" },
    { packed = true, tail = "2d8800" },
    { packed = true, tail = "94000000" },
    { packed = true, tail = "872d" },
    { packed = true, tail = "578000" },
    { packed = true, tail = "011100" },
    { packed = true, tail = "03880000" },
    { packed = true, tail = "843700" },
    { packed = true, tail = "f72d" },
    { packed = true, tail = "8bed" },
    { packed = true, tail = "aa090000" },
    { packed = true, tail = "0405" },
    { packed = true, tail = "02ca000000" },
    { packed = true, tail = "2f8500" },
    { packed = true, tail = "8f33000000" },
    { packed = true, tail = "420200" },
    { packed = true, tail = "03df" },
    { packed = true, tail = "6db6000000" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "6db60000" },
    { packed = true, tail = "6db600" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "6db600" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "b6db0000" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "6db6000000" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "db6d" },
    { packed = true, tail = "b6db" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "6db6000000" },
    { packed = true, tail = "b6db0000" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "b6db0000" },
    { packed = true, tail = "6db600" },
    { packed = true, tail = "b6db00" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "6db60000" },
    { packed = true, tail = "6db60000" },
    { packed = true, tail = "6db60000" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "b6db" },
    { packed = true, tail = "b6db" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "b6db" },
    { packed = true, tail = "6db600" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "db6d" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "b6db00" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "b6db" },
    { packed = true, tail = "db6d" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "6db600" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "b6db00" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "6db6" },
    { packed = true, tail = "b6db" },
    { packed = true, tail = "db6d" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "b6db" },
    { packed = true, tail = "6db600" },
    { packed = true, tail = "6db60000" },
    { packed = true, tail = "db6d000000" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "db6d000000" },
    { packed = true, tail = "db6d0000" },
    { packed = true, tail = "b6db00" },
    { packed = true, tail = "db6d000000" },
    { packed = true, tail = "6db60000" },
    { packed = true, tail = "db6d00" },
    { packed = true, tail = "b6db00" },
    { packed = true, tail = "b6db000000" },
    { packed = true, tail = "db6d000000" },
    { packed = true, tail = "90660000" },
    { packed = true, tail = "8e8e000000" },
    { packed = true, tail = "01ff000000" },
    { packed = true, tail = "db000000" },
    { packed = true, tail = "1b1b" },
    { packed = true, tail = "2429" },
    { packed = true, tail = "ffd40000" },
    { packed = true, tail = "05c2000000" },
    { packed = true, tail = "857100" },
    { packed = true, tail = "ff1e0000" },
    { packed = true, tail = "00010000" },
    { packed = true, tail = "2504" },
    { packed = true, tail = "dd0000" },
    { packed = true, tail = "02ff0000" },
    { packed = true, tail = "d4f80000" },
    { packed = true, tail = "6b9f000000" },
    { packed = true, tail = "ffd0000000" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "04100000" },
    { packed = true, tail = "1100" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "5700" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "018e0000" },
    { packed = true, tail = "ffe50000" },
    { packed = true, tail = "fff20000" },
    { packed = true, tail = "ffec0000" },
    { packed = true, tail = "4c9c" },
    { packed = true, tail = "0185000000" },
    { packed = true, tail = "02b600" },
    { packed = true, tail = "ffd3000000" },
    { packed = true, tail = "1bff00" },
    { packed = true, tail = "00040000" },
    { packed = true, tail = "8eff00" },
    { packed = true, tail = "d4f900" },
    { packed = true, tail = "ffde0000" },
    { packed = true, tail = "ffc80000" },
    { packed = true, tail = "ff8e" },
    { packed = true, tail = "29fd0000" },
    { packed = true, tail = "05de0000" },
    { packed = true, tail = "242900" },
    { packed = true, tail = "ffda0000" },
    { packed = true, tail = "def50000" },
    { packed = true, tail = "ff71" },
    { packed = true, tail = "8571" },
    { packed = true, tail = "1aff000000" },
    { packed = true, tail = "fd00000000" },
    { packed = true, tail = "f70000" },
    { packed = true, tail = "ff1b0000" },
    { packed = true, tail = "ff1b0000" },
    { packed = true, tail = "ffd400" },
    { packed = true, tail = "00ff0000" },
    { packed = true, tail = "b6b6" },
    { packed = true, tail = "1aff" },
    { packed = true, tail = "00f1" },
    { packed = true, tail = "1a1b000000" },
    { packed = true, tail = "c7fe0000" },
    { packed = true, tail = "00e600" },
    { packed = true, tail = "faff0000" },
    { packed = true, tail = "0185000000" },
    { packed = true, tail = "fb0000" },
    { packed = true, tail = "ffde000000" },
    { packed = true, tail = "c2ff" },
    { packed = true, tail = "1b1a0000" },
    { packed = true, tail = "240300" },
    { packed = true, tail = "1a1a00" },
    { packed = true, tail = "1b1a0000" },
    { packed = true, tail = "b600" },
    { packed = true, tail = "fe24000000" },
    { packed = true, tail = "ffee0000" },
    { packed = true, tail = "1a1b00" },
    { packed = true, tail = "f60000" },
    { packed = true, tail = "fe24000000" },
    { packed = true, tail = "00020000" },
    { packed = true, tail = "fffc0000" },
    { packed = true, tail = "01ff0000" },
    { packed = true, tail = "240100" },
    { packed = true, tail = "85710000" },
    { packed = true, tail = "0004" },
    { packed = true, tail = "71ff0000" },
    { packed = true, tail = "ff1b" },
    { packed = true, tail = "1b1a" },
    { packed = true, tail = "85710000" },
    { packed = true, tail = "ff1e00" },
    { packed = true, tail = "ffde" },
    { packed = true, tail = "2402000000" },
    { packed = true, tail = "2404" },
    { packed = true, tail = "ca0000" },
    { packed = true, tail = "c7c7000000" },
    { packed = true, tail = "01240000" },
    { packed = true, tail = "fa25" },
    { packed = true, tail = "d4f10000" },
    { packed = true, tail = "ff1b0000" },
    { packed = true, tail = "fe24" },
    { packed = true, tail = "feff000000" },
    { packed = true, tail = "03ff000000" },
    { packed = true, tail = "f224" },
    { packed = true, tail = "00d4000000" },
    { packed = true, tail = "24fe000000" },
    { packed = true, tail = "3041" },
    { packed = true, tail = "b3ab" },
    { packed = true, tail = "2e2500" },
    { packed = true, tail = "18140000" },
    { packed = true, tail = "1111000000" },
]
