# A bank of 38 images, in 5100/<n>.png.
compressed = true
bank = true
images = [
    { packed = false },
    { packed = true, tail = "8d00000000" },
    { packed = true, tail = "7f490000" },
    { packed = false },
    { packed = true, tail = "002e000000" },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = true, tail = "7f7f" },
    { packed = true, tail = "000d0000" },
    { packed = true, tail = "7f7f000000" },
    { packed = true, tail = "7f7f" },
    { packed = true, tail = "7f7f000000" },
    { packed = true, tail = "7f7f" },
    { packed = true, tail = "7f7f" },
    { packed = true, tail = "e67f00" },
    { packed = true, tail = "747f00" },
    { packed = true, tail = "024100" },
    { packed = true, tail = "7f7f" },
    { packed = true, tail = "477f00" },
    { packed = true, tail = "0d0c0000" },
    { packed = true, tail = "7f680000" },
    { packed = true },
    { packed = true, tail = "7e7f00" },
    { packed = true, tail = "111000" },
    { packed = true, tail = "7f7f000000" },
    { packed = true, tail = "e27f00" },
    { packed = true, tail = "0d0c0000" },
    { packed = true, tail = "7f7f000000" },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = true, tail = "7f7f" },
    { packed = true, tail = "2f35" },
    { packed = true, tail = "ad69000000" },
    { packed = true, tail = "61ab" },
    { packed = true, tail = "38ff0000" },
]
