# A bank of 204 images, in 10000/<n>.png.
compressed = true
bank = true
images = [
    { packed = true, tail = "ff0000" },
    { packed = true, tail = "acff0000" },
    { packed = true, tail = "bd05" },
    { packed = true, tail = "a4ea000000" },
    { packed = true, tail = "feff000000" },
    { packed = true, tail = "fc1d0000" },
    { packed = true, tail = "a4bd000000" },
    { packed = true, tail = "fdff" },
    { packed = true, tail = "fffa000000" },
    { packed = true, tail = "e70000" },
    { packed = true, tail = "fffe00" },
    { packed = true, tail = "0031000000" },
    { packed = true, tail = "ea0000" },
    { packed = true, tail = "ffa40000" },
    { packed = true, tail = "ffa4000000" },
    { packed = true, tail = "01fd00" },
    { packed = true, tail = "310000" },
    { packed = true, tail = "05a0" },
    { packed = true, tail = "ffa400" },
    { packed = true, tail = "3100" },
    { packed = true, tail = "24240000" },
    { packed = true, tail = "25250000" },
    { packed = true },
    { packed = true, tail = "2424000000" },
    { packed = true, tail = "2004" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "03000000" },
    { packed = true, tail = "003100" },
    { packed = true },
    { packed = true, tail = "ff000000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "7f7f000000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "a56b000000" },
    { packed = true, tail = "242400" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "2424000000" },
    { packed = true, tail = "2424" },
    { packed = true },
    { packed = true, tail = "31000000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "25250000" },
    { packed = true, tail = "1b280000" },
    { packed = true },
    { packed = true, tail = "b87a000000" },
    { packed = true, tail = "5a3b0000" },
    { packed = true, tail = "4a42" },
    { packed = true, tail = "b7ce00" },
    { packed = true, tail = "8c42000000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "24240000" },
    { packed = true, tail = "ffc000" },
    { packed = true, tail = "287f00" },
    { packed = true, tail = "24240000" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "ffff00" },
    { packed = true },
    { packed = true, tail = "242400" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "f50a000000" },
    { packed = true, tail = "26240000" },
    { packed = true, tail = "ff24" },
    { packed = true },
    { packed = false },
    { packed = true },
    { packed = true },
    { packed = true, tail = "9ca20000" },
    { packed = true },
    { packed = true, tail = "8c8c" },
    { packed = true },
    { packed = true, tail = "00310000" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "b38c00" },
    { packed = true, tail = "b2b20000" },
    { packed = true, tail = "9a9b00" },
    { packed = true, tail = "7dc5" },
    { packed = true, tail = "65650000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "ce2d00" },
    { packed = true, tail = "0034000000" },
    { packed = true },
    { packed = true, tail = "fe00000000" },
    { packed = true, tail = "edbd0000" },
    { packed = true, tail = "bd030000" },
    { packed = true, tail = "ffbd000000" },
    { packed = true, tail = "ff05" },
    { packed = true, tail = "ffd5" },
    { packed = true, tail = "d900" },
    { packed = true, tail = "fcbd0000" },
    { packed = true, tail = "ed00000000" },
    { packed = true },
    { packed = true, tail = "03ff00" },
    { packed = true, tail = "cccc000000" },
    { packed = true, tail = "cccc000000" },
    { packed = true, tail = "cccc" },
    { packed = true },
    { packed = true, tail = "232d" },
    { packed = true, tail = "2d23000000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "0034" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "000200" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "3480000000" },
    { packed = true, tail = "cccc000000" },
    { packed = true },
    { packed = true, tail = "89000000" },
    { packed = true },
    { packed = true, tail = "cccc000000" },
    { packed = true, tail = "0034000000" },
    { packed = true },
    { packed = true, tail = "cccc000000" },
    { packed = true },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "052d0000" },
    { packed = true, tail = "85cc" },
    { packed = true, tail = "3480000000" },
    { packed = true },
    { packed = true, tail = "232d00" },
    { packed = true, tail = "cccc0000" },
    { packed = true, tail = "cccc0000" },
    { packed = true, tail = "cccc0000" },
    { packed = true, tail = "cccc0000" },
    { packed = true, tail = "00340000" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "2d800000" },
    { packed = true, tail = "00230000" },
    { packed = true, tail = "80000000" },
    { packed = true },
    { packed = true, tail = "2d8a000000" },
    { packed = true, tail = "2dcc0000" },
    { packed = true },
    { packed = true, tail = "cccc0000" },
    { packed = true, tail = "17ff0000" },
    { packed = true, tail = "a4bd00" },
    { packed = true, tail = "a4fe00" },
    { packed = true, tail = "fabd0000" },
    { packed = true, tail = "feff" },
    { packed = false },
    { packed = false },
    { packed = true, tail = "ffbd00" },
    { packed = true, tail = "fcbd00" },
    { packed = false },
    { packed = true, tail = "0001000000" },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false },
    { packed = false, padding = [{ row = 0, bytes = "1d" }, { row = 3, bytes = "25" }, { row = 4, bytes = "25" }, { row = 5, bytes = "25" }, { row = 6, bytes = "1d" }, { row = 7, bytes = "7f" }] },
    { packed = true, tail = "980000" },
    { packed = true, tail = "cccc" },
    { packed = true },
    { packed = true },
    { packed = true },
    { packed = true, tail = "2dcc00" },
    { packed = true },
    { packed = true, tail = "0da7" },
    { packed = true },
    { packed = true },
    { packed = true, tail = "3400000000" },
    { packed = true },
    { packed = true },
]
